name: jellycat_tracker
description: A collection tracker for Jellycat enthusiasts.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
