name: Build iOS IPA

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Install Dependencies
        run: flutter pub get
        
      - name: Build iOS
        run: flutter build ios --release --no-codesign
        
      - name: Create IPA Folder
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload
          zip -r JellycatTracker.ipa Payload
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: JellycatTracker-IPA
          path: JellycatTracker.ipa
